version: "2"

services:
  api:
    build: api
    networks:
      - default
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/1
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - uploads:/app/uploads:rw

  celery:
    build: tasks
    networks:
      - default
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    restart: always
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads:rw
      - ./wordlists:/app/wordlists

  redis:
    image: redis:latest
    networks:
      - default
networks:
  default:

volumes:
  uploads:
